kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: allow-external-lb
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- NET_BIND_SERVICE
- NET_ADMIN
- NET_RAW
- SYS_TIME
- SETGID
- SETUID
- CHOWN
defaultAddCapabilities: []
requiredDropCapabilities:
- KILL
- MKNOD
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- awsElasticBlockStore
- azureDisk
- azureFile
- configMap
- downwardAPI
- emptyDir
- fc
- flexVolume
- gcePersistentDisk
- gitRepo
- glusterfs
- hostPath
- iscsi
- nfs
- persistentVolumeClaim
- projected
- quobyte
- rbd
- scaleIO
- secret
- storageos
- vsphereVolume
