apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: cafebot
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: cafebot
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_root_password
        - name: MYSQL_DATABASE
          value: your_database_name
        - name: MYSQL_USER
          value: your_mysql_user
        - name: MYSQL_PASSWORD
          value: your_mysql_password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql 
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: cafebot-pvc
