apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
  namespace: cafebot2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: spark
