apiVersion: v1
kind: PersistentVolume
metadata:
  name: cafebot-pv
  labels:
    type: do-block-storage
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany  # Adjust if needed
  persistentVolumeReclaimPolicy: Retain  # Adjust if needed
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4  # Adjust if needed
    volumeHandle: <volume-handle-from-do>