apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    annotations:
      cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
      meta.helm.sh/release-name: cert-manager
      meta.helm.sh/release-namespace: cert-manager
    creationTimestamp: "2023-11-24T09:17:48Z"
    generation: 2
    labels:
      app: webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: webhook
      app.kubernetes.io/version: v1.11.0
      helm.sh/chart: cert-manager-v1.11.0
    name: cert-manager-webhook
    resourceVersion: "586371"
    uid: fde761f6-fb8b-4eaf-bfde-968781f9b049
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3akNDQVVpZ0F3SUJBZ0lSQUs2N1gvVDBVM1BmK0RKTFZuZTQvWDh3Q2dZSUtvWkl6ajBFQXdNd0lqRWcKTUI0R0ExVUVBeE1YWTJWeWRDMXRZVzVoWjJWeUxYZGxZbWh2YjJzdFkyRXdIaGNOTWpNeE1USTBNRGt4TnpVeQpXaGNOTWpReE1USXpNRGt4TnpVeVdqQWlNU0F3SGdZRFZRUURFeGRqWlhKMExXMWhibUZuWlhJdGQyVmlhRzl2CmF5MWpZVEIyTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQTJJQUJObEFSeitCWlNTa1ZUbWpkdWUySFp0cFFZZUEKTEprTFBCYitxQ05lbTg3K2NVQzRFeFpVcEJZdTlrWG1SVnVvUlF1T2JNd2I4d1I1cGtDUjF4dzhRd1ZhNHdRNwpRbzFNa1ZTS2dKWGkvcjFjMXorZ09uNExFV1pPRzhyYmpsOTdrYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZPMStJMFZXRGlFS3JCRlZmQS9kb3V3bTZzb0YKTUFvR0NDcUdTTTQ5QkFNREEyZ0FNR1VDTUN0Z2NtYThNU1gzd3hrUVgreU1sVEoyNmVVY0JlVldFVDJTQWpWZApOcVFydGRDMnI3c0g2Vzl0WG0rdVc2Wk04d0l4QUlVYTA3a3VnVXQ5T1JhMDdzMDN3alFiVTdZd3l0OVZVclFPCnJWQjNRSTNkRWtIeTZ2cTRtOGtaSTJaWTgxTkgrdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: cert-manager-webhook
        namespace: cert-manager
        path: /validate
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: webhook.cert-manager.io
    namespaceSelector:
      matchExpressions:
      - key: cert-manager.io/disable-validation
        operator: NotIn
        values:
        - "true"
      - key: name
        operator: NotIn
        values:
        - cert-manager
    objectSelector: {}
    rules:
    - apiGroups:
      - cert-manager.io
      - acme.cert-manager.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - '*/*'
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    annotations:
      meta.helm.sh/release-name: ingress-nginx
      meta.helm.sh/release-namespace: ingress-nginx
    creationTimestamp: "2023-11-24T07:50:47Z"
    generation: 2
    labels:
      app.kubernetes.io/component: admission-webhook
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.9.4
      helm.sh/chart: ingress-nginx-4.8.4
    name: ingress-nginx-admission
    resourceVersion: "5010417"
    uid: de192d8b-2445-422f-ba39-80867c95d9e1
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkRENDQVJ1Z0F3SUJBZ0lRY2k0VllVUm92dkdBU3kxQmtLRHNOakFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1J1YVd3eE1DQVhEVEl6TVRFeU5EQTNORFUwTVZvWUR6SXhNak14TURNeE1EYzBOVFF4V2pBUApNUTB3Q3dZRFZRUUtFd1J1YVd3eE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUdZZUQ3UDlICnNwOGp4M00xZEVQOSt2NXl5UWRkUzN5UXNHdWo2VExXQVJpakdMdHF3MUprQXNySWZzS0c2S241WTBrS1hacUgKcldnM0FBcTdjS3lOMEtOWE1GVXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRgpCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkNjMmZUelp2Y0FnNkU3YXNrVzFyc2xaCmJ2N2ZNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJQVdIdDZWWkdGS2M1YTgrRU9ZTFZtNitvQVJZTW8yNlNaWm0KeXdNMU9qVHZBaUJxcnBiVVFOZGo5N0dPRmIzamZSY0RxRzFiN0REUVpjUXpxbkJIT0N3Z3d3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: ingress-nginx-controller-admission
        namespace: ingress-nginx
        path: /networking/v1/ingresses
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validate.nginx.ingress.kubernetes.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - networking.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - ingresses
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    annotations:
      meta.helm.sh/release-name: keda
      meta.helm.sh/release-namespace: keda
    creationTimestamp: "2023-12-04T11:24:25Z"
    generation: 2
    labels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: keda
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: keda-admission-webhooks
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.12.1
      helm.sh/chart: keda-2.12.1
    name: keda-admission
    resourceVersion: "4061854"
    uid: ab611629-1fbb-4bfc-9c63-7008794ff7fc
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFoTVJBd0RnWURWUVFLRXdkTFJVUkIKVDFKSE1RMHdDd1lEVlFRREV3UkxSVVJCTUI0WERUSXpNVEV5TkRBNU5UYzBNRm9YRFRNek1URXlNVEV3TlRjMApNRm93SVRFUU1BNEdBMVVFQ2hNSFMwVkVRVTlTUnpFTk1Bc0dBMVVFQXhNRVMwVkVRVENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTm5GcDhRUzkwQU14bnNhb3p5MlBkdUg2bE8yRVpjNDJBLzcKb01lU2c2U0h5b1lCU1Q1WUdvek9VQjJaUXVsTFcxZ3N1ZFhBZjlnNEhjSjJyL3hVUlpzbVNPUVpzR2xzeVMrSQo1VktXOHN0aEY5SlFYUytuYjVOV2d5K1dpd3dyV3c4cjFPMC9ES0NCNm1jeHF3T3FMT29VdmlGRHZ1WkZ6cDJLCmRBd01TK1UxRkhBUWhNcGRCcGVlbzBncVhpY0M3a1pPMlhyWlNtQTQyZzlRdXhIdDlqbEVLQlJiWDVYV1ovQm4KNDJENlhYRDJOUCtOeGZablc2TnlKYmpCRjNmUXp0OW8weWhQNXpqazh0enZEQjZ4eDdBdzdiTUsrRTJEb0tLcAphcngxWElTdU9JcERXMDd0T01hWmptL1pGQUVVb1VhZ2FRQkdDMDBjYkltUHlxTVJhWnNDQXdFQUFhTlRNRkV3CkRnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkRiN0Z1SDEKUFJEYWtybnZYZFdkLzF4YmxPV3VNQThHQTFVZEVRUUlNQWFDQkV0RlJFRXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUVlUCtwZ3lCVnA1ZktRbWFZV3RYL3pKeFljdGwwUU4vb2NHZXJWbzh2OVdjbmt4VVFwamt4YW9NVHVPCmVTbDUvU0wrVTNTMnlmbnVRMTdkcEVPejl2YUR5UmlscnFUQmxDTTNiOW5kbGFMRjVSblpQQnVNL2lSUHdNQVgKaEc1eUlGSWxPU2ZsMlYyTC9LWnArNWZINzl1NVpINmh6Q3JhWEtJWFVjVEFyaUZoTUF6cVlNU2tENG1IY1FOVApxNHJxT3BxQUcxK0dBZ2t3SG9vZW9XcE1uUHFsb1B3RmxLY0NRSGR3VWc2SGFHNDU0WWJBTkZmZWRZZ2xKVndsCklkZnVKN1F6dzNiNyt6U1ExWWgyWVNsN1N3cVY0UUtKVEF1ajViTVRJYy9qUnhqR3BxUzJ0YnRZMjFLcHM5UDAKRjhtb1ErRjZMYklUS3lRWXNXa2xxYjBCL3dJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: keda-admission-webhooks
        namespace: keda
        path: /validate-keda-sh-v1alpha1-scaledobject
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: vscaledobject.kb.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - keda.sh
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - scaledobjects
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    creationTimestamp: "2023-11-22T11:04:59Z"
    generation: 1
    labels:
      c3.doks.digitalocean.com/component: snapshot-validation
      c3.doks.digitalocean.com/plane: data
      doks.digitalocean.com/managed: "true"
    name: validation-webhook.snapshot.storage.k8s.io
    resourceVersion: "277"
    uid: 16fca632-a40c-4f0f-a3cf-4b0299a47c2a
  webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBRENDQXVpZ0F3SUJBZ0lRZTlsUUs5eUd0Y0cyTWJsRVBJS25tVEFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSXpNVEV5TWpFeE1EUTFPVm9YRFRJME1ESXlNREV4TURRMU9Wb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWxVUlVBSEhlSndhQ1FuWFNKT2EyRUVkRU9NSWhpTmFZUkd6ZkdNCnkyL1h1bGU2elhuUy95OTJ1Z1JLVkZGcTJnS3JBQjVhVFF6eC82NVJpVytlbC93cFJnZTR0akpiZFg1UkpsR0kKUmUrZDFsTXZHZmlhc0NndWRMaHk1ZHdTNFY1ekg3OTJYYndoZG1tTyt0TFFlZzdBL09nQ0lMajVYV0YwNWYyNwpkenNqRmN0blFQQUIwQXhzTDcwOU9uc1BySjh3SGdTcXl4ZytyN012anU3YkV3dDVxUTd1V1l1ejJiZStFWWVoCmkrdUVmcXBqUXJmL2FUbjFQSTNQN1JDRUVhSUpYRzFnZnRPTlJ2SC9rNTFvMkJURzI5bDljdEU4MVFDU0xZbEcKYTdtbExjclo4TG1Gb0VoNE1YTDdDR3FGRU9WdXg5WGxkUXVFRDVIcVJCT0IweTBDQXdFQUFhT0NBWFF3Z2dGdwpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3CkRBWURWUjBUQVFIL0JBSXdBRENDQVM4R0ExVWRFUUVCL3dTQ0FTTXdnZ0VmZ2hOemJtRndjMmh2ZEMxMllXeHAKWkdGMGFXOXVnamh6Ym1Gd2MyaHZkQzEyWVd4cFpHRjBhVzl1TGpsbU0yUmlaRFkyTFROa016Y3ROREE1WXkxaQpORGhrTFRjeE5UWmlOVEF3T1RFMU40SThjMjVoY0hOb2IzUXRkbUZzYVdSaGRHbHZiaTQ1WmpOa1ltUTJOaTB6ClpETTNMVFF3T1dNdFlqUTRaQzAzTVRVMllqVXdNRGt4TlRjdWMzWmpna1J6Ym1Gd2MyaHZkQzEyWVd4cFpHRjAKYVc5dUxqbG1NMlJpWkRZMkxUTmtNemN0TkRBNVl5MWlORGhrTFRjeE5UWmlOVEF3T1RFMU55NXpkbU11WTJ4MQpjM1JsY29KS2MyNWhjSE5vYjNRdGRtRnNhV1JoZEdsdmJpNDVaak5rWW1RMk5pMHpaRE0zTFRRd09XTXRZalE0ClpDMDNNVFUyWWpVd01Ea3hOVGN1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQUQKZ2dFQkFCd0Q1UnEzZkVKM0lScWlSN1JtZnpxWjI2V1FqdndLb2tma0JpMDBxTjVoMWY3djY1VnBHS2k5ckdlcAo0QlVleUNBMDQxWURaakRUZDBkQ3pQUTBONnUvNHdxUFRNYkdOTUF6elFNTWIwWGJpamdBMldWYVR3N080dUNjCkRRZ0FYNGk4cG9LNlpxaVBWUUZubkV6NHpIT1Vnd1IwYldzNTZIbDRZSE1yTFkxdjZmdjI0UEZ3VUF3dXNOaFkKd1JheGpjazlaQ1NuNTMvbmY1amMra2ZKVktUMTNpTmlPQnQ2RWs2cnNyNVFsVWhzd054bGs5NHNTNjNIeDErZgo4MEpZT0pGMzQ2WjQ1MDRCbWJTb3BTYUZYZ2syR09GUGk3UCsyRVc5L2paK05WeWFhTjdoWmdzUEdtTlM3Z00wClc4ZCtMbmNwMW9FcDJPRjR4S1AzelhVMzMwcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      url: https://snapshot-validation/volumesnapshot
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation-webhook.snapshot.storage.k8s.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - snapshot.storage.k8s.io
      apiVersions:
      - v1
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - volumesnapshots
      - volumesnapshotcontents
      - volumesnapshotclasses
      scope: '*'
    sideEffects: None
    timeoutSeconds: 15
kind: List
metadata:
  resourceVersion: ""
