apiVersion: v1
kind: Pod
metadata:
  name: spark-history-server
  namespace: cafebot2
  labels:
    app: spark-history-server
spec:
  containers:
  - name: spark-history-server
    image: shekharzxcv/spark-py:latest
    command: ["/opt/spark/bin/spark-class", "-Dspark.history.fs.logDirectory=/data/", "org.apache.spark.deploy.history.HistoryServer"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
    ports:
    - containerPort: 18080
    readinessProbe:
      timeoutSeconds: 4
      httpGet:
        path: /
        port: 18080
    livenessProbe:
      timeoutSeconds: 4
      httpGet:
        path: /
        port: 18080
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: spark-pvc
      readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-service
  namespace: cafebot2
  labels:
    app: spark-history-server
spec:
  ports:
  - port: 18080
    targetPort: 18080
  selector:
    app: spark-history-server
